export const categoryBlog = [
    "Technology",
    "Science",
    "Health",
    "Business",
    "Sports",
    "Education",
    "Travel",
    "Food",
    "React",
    "JavaScript",
    "Node",
    "Express",
    "MongoDB",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring",
    "C++",
    "C#",
    "HTML",
    "CSS",
    "Bootstrap",
    "Tailwind",
    "Material-UI",
    "Chakra-UI",
    "Ant Design",
    "GraphQL",
    "Apollo",
    "REST API",
    "WebSockets",
    "Socket.IO",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "AWS",
    "Azure",
    "GCP",
    "Firebase",
    "Heroku",
    "Netlify",
    "Vercel",
    "Nginx",
    "Apache",
    "Linux",
    "Ubuntu",
    "CentOS",
    "Debian",
    "Fedora",
    "Arch",
    "Windows",
    "MacOS",
    "iOS",
    "Android",
    "VS Code",
    "Sublime Text",
    "Atom",
    "Vim",
    "Eclipse",
    "IntelliJ",
    "PyCharm",
    "WebStorm",
    "Visual Studio",
    "Postman",
    "Insomnia",
    "Swagger",
    "Jira",
    "Confluence",
    "Trello",
    "Slack",
    "Zoom",
    "Google Meet",
    "Microsoft Teams",
    "Discord",
    "WhatsApp",
    "Telegram",
    "Signal",
    "Facebook",
    "Twitter",
    "LinkedIn",
    "Instagram",
    "Snapchat",
    "TikTok",
    "YouTube",
    "Netflix",
    "Prime Video",
    "Disney+",
    "Hulu",
    "Spotify",
    "Apple Music",
    "YouTube Music",
    "Tidal",
    "SoundCloud",
    "Podcast",
    "Blog",
    "Vlog",
    "Book",
    "Movie",
    "TV Show",
    "Entertainment",
    "Education",
    "Travel",
    "Food",
    "Other",
]
